@startuml C4_Elements
    actor Ususário
    
    Ususário -> Front_end: Acessa
    Front_end -> solicitarPagamentoService: cria solicitação de post
    solicitarPagamentoService -> PagamentoController: solicita fatura pagamento
    PagamentoController -> PagamentoAS: gera solicitação fatura
    PagamentoAS -> ServiçoPaypal: solicita fatura pagamento
    alt success
        PagamentoAS <-- ServiçoPaypal: success
        PagamentoController <-- PagamentoAS: success
        solicitarPagamentoService <-- PagamentoController: success
        Front_end <-- solicitarPagamentoService: success        
        Ususário <-- Front_end: success
    else failure
        PagamentoAS <-- ServiçoPaypal: failure
        PagamentoController <-- PagamentoAS: failure
        solicitarPagamentoService <-- PagamentoController: failure        
        Front_end <-- solicitarPagamentoService: failure        
        Ususário <-- Front_end: failure
    end
@enduml